# Generated by Django 2.2.10 on 2020-09-21 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Описание')),
                ('sort', models.IntegerField(blank=True, default=0, verbose_name='Номер для сортировки')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Активен ли объект')),
            ],
            options={
                'verbose_name': 'Базовая модель',
                'verbose_name_plural': 'Базовые модели',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('related_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='coreapp.CoreModel', verbose_name='images')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
