# Generated by Django 2.2.10 on 2020-09-21 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('coremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreapp.CoreModel')),
                ('question_text', models.TextField(max_length=1024, verbose_name='Имя участника')),
                ('question_type', models.CharField(choices=[('a', 'Single choice'), ('b', 'Multiple choice'), ('c', 'Text answer')], max_length=1)),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
            bases=('coreapp.coremodel', models.Model),
        ),
        migrations.CreateModel(
            name='PollEventModel',
            fields=[
                ('coremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreapp.CoreModel')),
                ('date_start', models.DateTimeField(null=True, verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(null=True, verbose_name='Дата завершения')),
                ('votes_limit', models.PositiveIntegerField(null=True, verbose_name='Лимит голосов для досрочного завершения')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.QuestionModel', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'голосование',
                'verbose_name_plural': 'Голосования',
            },
            bases=('coreapp.coremodel', models.Model),
        ),
    ]
