# Generated by Django 2.2.10 on 2020-09-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreapp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('coremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreapp.CoreModel')),
                ('type', models.CharField(choices=[(1, 'radio'), (2, 'checkbox'), (3, 'text')], default='radio', max_length=8, verbose_name='Тип вопроса')),
                ('text', models.CharField(max_length=2048, verbose_name='Текст вопроса')),
            ],
            bases=('coreapp.coremodel', models.Model),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('coremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreapp.CoreModel')),
                ('text', models.CharField(max_length=2048, verbose_name='Текст варианта')),
                ('correct', models.BooleanField(default=False, verbose_name='Вариант верен?')),
                ('from_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Question', verbose_name='Вопрос')),
            ],
            bases=('coreapp.coremodel', models.Model),
        ),
    ]
