# Generated by Django 2.2.10 on 2020-09-25 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('coremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreapp.CoreModel')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
            bases=('coreapp.coremodel', models.Model),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Заголовок')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Активен ли вопрос')),
                ('type', models.IntegerField(choices=[(1, 'One option answer'), (2, 'Multiple options answer'), (3, 'Text answer')], default=1, verbose_name='Тип вопроса')),
                ('text', models.CharField(max_length=2048, verbose_name='Текст вопроса')),
                ('from_quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Quiz', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('coremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreapp.CoreModel')),
                ('text', models.CharField(max_length=2048, verbose_name='Текст варианта')),
                ('correct', models.BooleanField(default=False, verbose_name='Вариант верен?')),
                ('from_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
            bases=('coreapp.coremodel', models.Model),
        ),
        migrations.CreateModel(
            name='AnswerText',
            fields=[
                ('coremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreapp.CoreModel')),
                ('user', models.CharField(max_length=2048, verbose_name='ПОльзователь')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('answered_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Question', verbose_name='Вопрос')),
                ('text_answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Choice', verbose_name='Текст ответа')),
            ],
            options={
                'verbose_name': 'Ответ тектом',
                'verbose_name_plural': 'Ответы тектом',
            },
            bases=('coreapp.coremodel', models.Model),
        ),
        migrations.CreateModel(
            name='AnswersMultiChoice',
            fields=[
                ('coremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreapp.CoreModel')),
                ('user', models.CharField(max_length=2048, verbose_name='ПОльзователь')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('answered_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Question', verbose_name='Вопрос')),
                ('multi_choice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Choice', verbose_name='Выбранный вариант')),
            ],
            options={
                'verbose_name': 'Ответ несколькими вариантами',
                'verbose_name_plural': 'Ответы несколькими вариантами',
            },
            bases=('coreapp.coremodel', models.Model),
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('coremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreapp.CoreModel')),
                ('user', models.CharField(max_length=2048, verbose_name='ПОльзователь')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('answered_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Question', verbose_name='Вопрос')),
                ('single_choice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Choice', verbose_name='Выбранный вариант')),
            ],
            options={
                'verbose_name': 'Ответ единственным вариантом',
                'verbose_name_plural': 'Ответы единственным вариантом',
            },
            bases=('coreapp.coremodel', models.Model),
        ),
    ]
